.TH "inc Directory Reference" 3 "Sun Jun 23 2024" "Version v5.0.0" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfile_concepts\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmagic\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmagic_exception\&.hpp\fP"
.br
.ti -1c
.RI "file \fButility\&.hpp\fP"
.br
.in -1c
