.TH "magic_exception.hpp" 3 "Sun Mar 16 2025 12:53:51" "Version v5.6.0" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
magic_exception.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <format>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrecognition::magic_exception\fP"
.br
.RI "The base class for all exceptions thrown by the magic class\&. "
.ti -1c
.RI "class \fBrecognition::empty_path\fP"
.br
.ti -1c
.RI "class \fBrecognition::invalid_path\fP"
.br
.ti -1c
.RI "class \fBrecognition::magic_is_closed\fP"
.br
.ti -1c
.RI "class \fBrecognition::magic_open_error\fP"
.br
.ti -1c
.RI "class \fBrecognition::magic_load_error\fP"
.br
.ti -1c
.RI "class \fBrecognition::magic_file_error\fP"
.br
.ti -1c
.RI "class \fBrecognition::magic_set_flags_error\fP"
.br
.ti -1c
.RI "class \fBrecognition::magic_set_param_error\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrecognition\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
