.TH "md_SECURITY" 3 "Sat Feb 15 2025 23:18:44" "Version v5.3.1" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_SECURITY \- Security Policy 
.PP

.SH "Supported Versions"
.PP
Version   Supported    5\&.3\&.x   +    5\&.2\&.x   -    5\&.1\&.x   -    5\&.0\&.x   -    < 5\&.0   -   
.SH "Reporting a Vulnerability"
.PP
If you discover a security vulnerability in Libmagicxx, we would appreciate your help in disclosing it to us in a responsible manner\&. To report a vulnerability, please follow these steps:

.PP
.IP "1." 4
\fBEmail the Vulnerability\fP: Send an email to \fRoguz\&.toraman@tutanota\&.com\fP with the details of the vulnerability\&. Please include:
.IP "  \(bu" 4
A detailed description of the vulnerability
.IP "  \(bu" 4
Steps to reproduce the vulnerability
.IP "  \(bu" 4
Any potential impact or severity
.IP "  \(bu" 4
Your contact information
.PP

.IP "2." 4
\fBResponse Time\fP: We aim to respond to vulnerability reports within 48 hours\&. You will receive an initial confirmation that we have received your report\&.
.IP "3." 4
\fBUpdates\fP: We will provide regular updates on the status of your report\&. Expect an update at least once a week while we investigate and address the issue\&.
.IP "4." 4
\fBHandling the Report\fP:
.IP "  \(bu" 4
If the vulnerability is accepted, we will work on a fix and credit you in the release notes unless you prefer to remain anonymous\&.
.IP "  \(bu" 4
If the vulnerability is declined, we will provide a detailed explanation as to why it was not accepted\&.
.PP

.IP "5." 4
\fBDisclosure Policy\fP: We ask that you do not publicly disclose the vulnerability until we have had a chance to investigate and address it\&. We are committed to addressing all vulnerabilities promptly and will work with you to coordinate an appropriate disclosure timeline\&.
.PP

.PP
Thank you for helping to keep Libmagicxx and our community secure\&. 
