.TH "md_TODO" 3 "Sun Feb 16 2025 11:10:00" "Version v5.3.2" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_TODO \- To Do 
.PP


.PP
.IP "\(bu" 2
[ ] Use modules\&.
.IP "\(bu" 2
[ ] Build as a CMake package\&.
.IP "\(bu" 2
[ ] Build as an RPM package\&.
.IP "\(bu" 2
[ ] Cross compile for Windows and macOS\&.
.IP "\(bu" 2
[ ] Use docker for the development environment 
.PP

