.TH "md_TODO" 3 "Thu Feb 13 2025 23:22:52" "Version v5.2.0" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_TODO \- To Do 
.PP


.PP
.IP "\(bu" 2
[ ] Use modules\&.
.IP "\(bu" 2
[ ] Build as a CMake package\&.
.IP "\(bu" 2
[ ] Build as an RPM package\&.
.IP "\(bu" 2
[ ] Cross compile for Windows and macOS\&.
.IP "\(bu" 2
[ ] Use docker for the development environment 
.PP

