.TH "recognition::magic_is_closed" 3 "Tue Jun 25 2024 23:14:54" "Version v5.1.1" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recognition::magic_is_closed
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <magic_exception\&.hpp>\fP
.PP
Inherits \fBrecognition::magic_exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmagic_is_closed\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBrecognition::magic_exception\fP
.in +1c
.ti -1c
.RI "\fBmagic_exception\fP (const std::string &error)"
.br
.RI "Construct \fBmagic_exception\fP with an error message\&. "
.ti -1c
.RI "\fBmagic_exception\fP (const std::string &function, const std::string &error)"
.br
.RI "Construct \fBmagic_exception\fP with an error message and the name of the funtion where the error occurred\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "recognition::magic_is_closed::magic_is_closed ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
