.TH "recognition::magic_load_error" 3 "Sat Feb 15 2025 22:17:11" "Version v5.3.0" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recognition::magic_load_error
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <magic_exception\&.hpp>\fP
.PP
Inherits \fBrecognition::magic_exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmagic_load_error\fP (const std::string &error, const std::string &database_file_path)"
.br
.in -1c

Public Member Functions inherited from \fBrecognition::magic_exception\fP
.in +1c
.ti -1c
.RI "\fBmagic_exception\fP (const std::string &error)"
.br
.RI "Construct \fBmagic_exception\fP with an error message\&. "
.ti -1c
.RI "\fBmagic_exception\fP (const std::string &function, const std::string &error)"
.br
.RI "Construct \fBmagic_exception\fP with an error message and the name of the funtion where the error occurred\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "recognition::magic_load_error::magic_load_error (const std::string & error, const std::string & database_file_path)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
