.TH "recognition::magic_open_error" 3 "Sun Apr 13 2025 19:46:45" "Version v6.0.0" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recognition::magic_open_error
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <magic_exception\&.hpp>\fP
.PP
Inherits \fBrecognition::magic_exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmagic_open_error\fP (const std::string &error)"
.br
.in -1c

Public Member Functions inherited from \fBrecognition::magic_exception\fP
.in +1c
.ti -1c
.RI "\fBmagic_exception\fP (const std::string &function, const std::string &error)"
.br
.RI "Construct \fBmagic_exception\fP with an error message and the name of the funtion where the error occurred\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "recognition::magic_open_error::magic_open_error (const std::string & error)\fR [inline]\fP, \fR [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
