.TH "recognition::magic_exception" 3 "Sun Mar 23 2025 13:15:52" "Version v5.7.0" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recognition::magic_exception \- The base class for all exceptions thrown by the magic class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <magic_exception\&.hpp>\fP
.PP
Inherits std::runtime_error\&.
.PP
Inherited by \fBrecognition::empty_path\fP, \fBrecognition::invalid_path\fP, \fBrecognition::magic_file_error\fP, \fBrecognition::magic_is_closed\fP, \fBrecognition::magic_load_error\fP, \fBrecognition::magic_open_error\fP, \fBrecognition::magic_set_flags_error\fP, and \fBrecognition::magic_set_param_error\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmagic_exception\fP (const std::string &function, const std::string &error)"
.br
.RI "Construct \fBmagic_exception\fP with an error message and the name of the funtion where the error occurred\&. "
.in -1c
.SH "Detailed Description"
.PP 
The base class for all exceptions thrown by the magic class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "recognition::magic_exception::magic_exception (const std::string & function, const std::string & error)\fR [inline]\fP"

.PP
Construct \fBmagic_exception\fP with an error message and the name of the funtion where the error occurred\&. 
.PP
\fBParameters\fP
.RS 4
\fIfunction\fP The name of the funtion\&. 
.br
\fIerror\fP The description of the error\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
