.TH "recognition::magic::magic_private::flags_converter" 3 "Thu Mar 6 2025 21:52:38" "Version v5.5.1" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recognition::magic::magic_private::flags_converter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBflags_converter\fP (const \fBflags_container_t\fP &flags_container) noexcept"
.br
.ti -1c
.RI "\fBflags_converter\fP (\fBflags_mask_t\fP flags_mask) noexcept"
.br
.ti -1c
.RI "\fBoperator libmagic_value_t\fP () const noexcept"
.br
.ti -1c
.RI "\fBoperator flags_container_t\fP () const"
.br
.ti -1c
.RI "\fBoperator libmagic_value_name_t\fP () const"
.br
.ti -1c
.RI "\fBoperator flags_mask_t\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBflags_mask_t\fP \fBm_flags_mask\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "recognition::magic::magic_private::flags_converter::flags_converter (const \fBflags_container_t\fP & flags_container)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SS "recognition::magic::magic_private::flags_converter::flags_converter (\fBflags_mask_t\fP flags_mask)\fR [inline]\fP, \fR [explicit]\fP, \fR [noexcept]\fP"

.SH "Member Function Documentation"
.PP 
.SS "recognition::magic::magic_private::flags_converter::operator \fBflags_container_t\fP () const\fR [inline]\fP"

.SS "recognition::magic::magic_private::flags_converter::operator \fBflags_mask_t\fP () const\fR [inline]\fP"

.SS "recognition::magic::magic_private::flags_converter::operator \fBlibmagic_value_name_t\fP () const\fR [inline]\fP"

.SS "recognition::magic::magic_private::flags_converter::operator \fBlibmagic_value_t\fP () const\fR [inline]\fP, \fR [noexcept]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const \fBflags_mask_t\fP recognition::magic::magic_private::flags_converter::m_flags_mask"


.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
