.TH "utility.hpp" 3 "Sun Jun 23 2024" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <ranges>\fP
.br
\fC#include <concepts>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <functional>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fButility\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename ContainerType , typename StringConverterType > requires std::ranges::range< ContainerType > && \fButility::requires\fP (ContainerType c)"
.br
.RI "Convert any container to string using the string_converter\&. "
.ti -1c
.RI "std::string \fButility::to_string\fP (const ContainerType &container, const std::string &value_separator, StringConverterType string_converter)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
