.TH "utility::range_container" 3 "Sun Mar 16 2025 14:35:10" "Version v5.6.2" "Libmagicxx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility::range_container \- Define requirements for a range container\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <utility\&.hpp>\fP
.SH "Concept definition"
.PP 

.nf
template<typename ContainerType>
concept utility::range_container =  std::ranges::range<ContainerType>
                       && requires(ContainerType c) {
                              typename ContainerType::value_type;
                          }
.PP
.fi
.SH "Detailed Description"
.PP 
Define requirements for a range container\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIContainerType\fP The type of the container\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Libmagicxx from the source code\&.
