#!/usr/bin/bash
#
# SPDX-FileCopyrightText: Copyright (c) 2024 Oğuz Toraman <oguz.toraman@tutanota.com>
# SPDX-License-Identifier: LGPL-3.0-only

echo "Building libmagicxx and running the unit tests before committing..."

cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DBUILD_MAGICXX_TESTS=ON -DCMAKE_CXX_COMPILER:FILEPATH=g++ -S. -Btest_build -G Ninja &&
cd test_build &&
ninja -j10 &&
cd test &&
ctest --output-on-failure -j10
