name: Build and Test on Linux using CLANG

on:
  pull_request:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  clang_build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Install dependencies.
      run: dnf install -y cmake make ninja-build clang libcxx-devel git autoconf libtool
    - name: Clone Libmagicxx.
      run: git clone https://github.com/oguztoraman/libmagicxx /libmagicxx
    - name: Build.
      working-directory: /libmagicxx
      run: ./scripts/build.sh -c clang++
    - name: Tests.
      working-directory: /libmagicxx
      shell: bash
      run: ./scripts//build.sh -c clang++ -t
    - name: Examples.
      working-directory: /libmagicxx
      shell: bash
      run: ./scripts//build.sh -c clang++ -e
