name: Build and Test on Linux using GCC

on:
  pull_request:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  gcc_build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Install dependencies.
      run: dnf install -y cmake make ninja-build g++ git autoconf libtool
    - name: Clone Libmagicxx.
      run: git clone https://github.com/oguztoraman/libmagicxx /libmagicxx
    - name: Build (Shared library).
      working-directory: /libmagicxx
      run: ./scripts/workflows.sh -p gcc-shared-release
    - name: Tests (Shared library).
      working-directory: /libmagicxx
      run: ./scripts/workflows.sh -p gcc-shared-tests-release
    - name: Examples (Shared library).
      working-directory: /libmagicxx
      run: ./scripts/workflows.sh -p gcc-shared-examples-release
    - name: Build (Static library).
      working-directory: /libmagicxx
      run: ./scripts/workflows.sh -p gcc-static-release
    - name: Tests (Static library).
      working-directory: /libmagicxx
      run: ./scripts/workflows.sh -p gcc-static-tests-release
    - name: Examples (Static library).
      working-directory: /libmagicxx
      run: ./scripts/workflows.sh -p gcc-static-examples-release