name: Build and Test on Linux using CLANG
permissions:
  contents: read
on:
  pull_request:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  clang_build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Install Git.
      run: dnf install -y git
    - name: Checkout.
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build (Shared library).
      run: ./scripts/workflows.sh -p linux-x86_64-clang-shared-release
    - name: Tests (Shared library).
      run: ./scripts/workflows.sh -p linux-x86_64-clang-shared-tests-release
    - name: Examples (Shared library).
      run: ./scripts/workflows.sh -p linux-x86_64-clang-shared-examples-release
    - name: Build (Static library).
      run: ./scripts/workflows.sh -p linux-x86_64-clang-static-release
    - name: Tests (Static library).
      run: ./scripts/workflows.sh -p linux-x86_64-clang-static-tests-release
    - name: Examples (Static library).
      run: ./scripts/workflows.sh -p linux-x86_64-clang-static-examples-release
