name: Build and Test on Linux using GCC
permissions:
  contents: read
on:
  pull_request:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  gcc_build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Checkout.
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Dependencies.
      run: /scripts/install_dependencies.sh
    - name: Build (Shared library).
      run: ./scripts/workflows.sh -p linux-x86_64-gcc-shared-release
    - name: Tests (Shared library).
      run: ./scripts/workflows.sh -p linux-x86_64-gcc-shared-tests-release
    - name: Examples (Shared library).
      run: ./scripts/workflows.sh -p linux-x86_64-gcc-shared-examples-release
    - name: Build (Static library).
      run: ./scripts/workflows.sh -p linux-x86_64-gcc-static-release
    - name: Tests (Static library).
      run: ./scripts/workflows.sh -p linux-x86_64-gcc-static-tests-release
    - name: Examples (Static library).
      run: ./scripts/workflows.sh -p linux-x86_64-gcc-static-examples-release
