name: Build and Test on Linux using GCC

on:
  pull_request:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  gcc_build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Install dependencies.
      run: dnf install -y cmake make ninja-build g++ git autoconf libtool
    - name: Clone Libmagicxx.
      run: git clone https://github.com/oguztoraman/libmagicxx /libmagicxx
    - name: Build.
      working-directory: /libmagicxx
      run: ./build.sh -c g++
    - name: Test.
      working-directory: /libmagicxx
      run: ./build.sh -c g++ -t
